// lib/formLabels.ts
export const FORM_LABELS: Record<string, string> = {
  fullName:            "الاسم الكامل",
  discordTag:          "اسم مستخدم ديسكورد مع الرقم",
  age:                 "العمر",
  timezone:            "الدولة",
  gameLevel:           "مستواك (1-10)",
  gameLevelReason:     "سبب التقييم",
  hoursPerWeek:        "عدد الساعات أسبوعياً",
  similarModes:        "أطوار مشابهة جربتها",
  joinReason:          "سبب رغبتك في الانضمام",
  preferPhase:         "تفضيلك (التخطيط / التنفيذ)",
  preferPhaseReason:   "سبب التفضيل",
  roleRequested:       "تخصصك",
  acceptYoungerLeader: "أستطيع العمل تحت قيادة شخص أصغر",
  disagreeMission:     "تصرفك إذا كُلّفت بمهمة ضد رأيك",
  ambushFirstStep:     "أول خطوة في حالة الكمين",
  openFieldTactics:    "تكتيكك في خريطة مفتوحة ضد قناصين",
  teammateRevealed:    "تصرفك مع لاعب كشف الموقع",
  missionVsTeam:       "الأولوية (المهمة أم السلامة)",
  silentMissionNoise:  "تصرفك مع زميل مزعج",
  trainNewbies:        "التعامل مع لاعبين أقل خبرة",
  buildingEntry:       "خطة دخول مبنى مشبوه",
  commsScore:          "التواصل (1-10)",
  ordersScore:         "تنفيذ الأوامر (1-10)",
  pressureScore:       "اتخاذ القرار (1-10)",
  teamworkScore:       "العمل الجماعي (1-10)",
  weaknesses:          "نقاط الضعف",
  strengths:           "نقاط القوة",
  commitment:          "التزامك بالجداول",
  kickedBefore:        "هل سبق وتم طردك؟",
  kickReason:          "سبب الطرد",
  freeSpace:           "مساحة حرّة",
};
